.\" Manpage for csvcut.
.\" Contact gati.gergely@gmail.com to correct errors or typos.
.TH man 1 "23 Mar 2024" "1.0" "csvcut man page"
.SH NAME
csvcut \- select/process columns from csv files
.SH SYNOPSIS
csvcut [-f list] [-H] [-o csv|json|xml] [-d delim] [-D output-delim] [-c field:cmd] [file ...]
.SH DESCRIPTION
csvcut is a cut implementation for csv files.
Parsing the input as csv formatted text file according to RFC 4180 with the exception that line
ending is based on the system default.
.SH OPTIONS
.TP
.BI "\-f " fields
Select fields. This could be one range or several ranges separated by comma.
A range is one of the following:

.RS
.TP
N
N'th field counting from 1
.TP
N\-
N'th field and all following fields
.TP
N\-M
fields between N'th and M'th including both given fields
.TP
\fB\-M\fR
all fields from the first to M'th
.RE

.TP
.B \-H
Skip the first row from the output. The first row usually the header for csv
files. This option is implicitly set when choosing an output format other
than csv.

.TP
.BI "\-d " delim
Choose a delimiter for the input csv. Default is a comma ',' character.

.TP
.BI "\-D " delim
Choose a delimiter for the output csv. Default is a comma ',' character.
This option is ignored for any output format except csv.

.TP
.BI "\-o " format
Specify the output format. Default is 'csv'. Choose from the following
formats:
.TP
.RS
.TP
csv
Default csv format
.TP
json
JSON output. Requires csv input with header row. The \fB\-H\fR option is implicitly set
.TP
xml
XML output. Requires csv input with header row. The \fB\-H\fR option is implicitly set.
.RE

.TP
.BI "\-c " field:command
For the specified field, calls the given command and the standard output
from the command will be placed instead of the field actual value. 
Two ranges can be specified, separated by a forward slash '/' character.
The first range should be one field or a single range and selects the fields
needs top be rewritten. The second rangeset may contain multiple ranges
separated by comma ',' character and the selected fields are passed to the
processing command as extra arguments.
Can be used multiple times for different fields. The
passed arguments to the command:
.TP
.RS

.TP
1
column number in the input file
.TP
2
column number in the output file
.TP
3
name of the field, according to the header row
.TP
4
actual field value
.TP
5+
extra arguments specified by the second range set
.RE

.TP
.B \-h
Summary of command line arguments and exit

.SH EXAMPLES

$ csvcut -H -f 1-3,5,9- -c 2-3/6,8-9:pf_1 -c 5/2,4:pf_2 input.csv

This command will process input.csv, outputting 1,2,3,5,9 and all the rest of
the columns with processing of 2nd, 3rd and 5th fields, omitting the first
row. The columns 2 and 3
will be processed by an executable called pf_1 which will receive the
following arguments when called for the column 3:
.TP
1
column number in input, value 3
.TP
2
column number in output, value 3
.TP
3
name of the field, the 3rd field of the first row of the input
.TP
4
the value of the 3rd field of the current row
.TP
5
the value of the 6th field of the current row
.TP
6
the value of the 8th field of the current row
.TP
7
the value of the 9th field of the current row
.RE

The standard output will be used as the column 3 of the generated output.
The column 5 will be processed by the executable called pf_2 and the extra
arguments will be the current values of the second and forth columns.

.SH SEE ALSO
cut(1), jq(1), xmllint(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Gergely Gati (gati.gergely@gmail.com)
.SH COPYRIGHT
Copyright \(co 2024 Gergely Gati
.P
BSD-3-Clause license
